package org.university.db.project.tinytwitter.dao;

import java.util.List;

import org.apache.ibatis.annotations.*;
import org.university.db.project.tinytwitter.entity.Blog;

@Mapper
public interface BlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbggenerated
     */
    @Delete("delete from blog where blog_id = #{blogId}")
    int deleteByPrimaryKey(Integer blogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbggenerated
     */
    @Insert("insert into blog (title, create_date, update_date, author, content) " +
            "values (#{title}, #{createDate}, #{updateDate}, #{author}, #{content})")
    int insert(Blog record);

    @Select("select blog_id from blog where title = #{title}")
    int getIdByTitle(String title);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbggenerated
     */
    Blog selectByPrimaryKey(Integer blogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbggenerated
     */
    @Select("select blog_id, title, create_date, update_date, author, content from blog")
    @Result(column = "blog_id", property = "blogId")
    List<Blog> selectAll();

    List<Blog> find(String string);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbggenerated
     */
    @Update("update blog set title = #{title}," +
            "      create_date = #{createDate}," +
            "      update_date = #{updateDate}," +
            "      author = #{author}," +
            "      content = #{content}" +
            "    where blog_id = #{blogId}")
    int updateByPrimaryKey(Blog record);
}